package uk.gov.hmrc.helpers

import play.api.libs.json.Json
import uk.gov.hmrc.decisionservice.model.api.DecisionRequest

trait CaseNewTestData {


  // scalastyle:off


  val decisionCase1a = """{"version":"1.5.0-final","correlationID":"session-149274dd-0261-4da9-8b68-6131932bb6dd","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""

  val decisionRespone1 = """{"version":"1.5.0-final","correlationID":"session-12345","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

   val decisionCase1e = """{"version":"1.5.0-final","correlationID":"session-149274dd-0261-4da9-8b68-6131932bb6dd","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithoutPermission","workerDecidingHowWorkIsDone":"workerAgreeWithOthers","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"workerCannotChoose"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"asPartOfUsualRateInWorkingHours"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""

  val decisionRespone1e = """{"version":"1.5.0-final","correlationID":"session-12345","score":{"partAndParcel":"LOW","financialRisk":"LOW","personalService":"HIGH","exit":"CONTINUE","control":"HIGH","setup":"CONTINUE"},"result":"Inside IR35"}"""



  val decisionCase2a = """{"version":"1.5.0-final","correlationID":"session-829e8d15-3699-4988-b825-94c59db392a7","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""

  val decisionRespone2 = """{"version":"1.5.0-final","correlationID":"session-12345","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase2e = """{"version":"1.5.0-final","correlationID":"session-829e8d15-3699-4988-b825-94c59db392a7","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithoutPermission","workerDecidingHowWorkIsDone":"workerDecidesWithoutInput","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"workerCannotChoose"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"asPartOfUsualRateInWorkingHours"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""

  val decisionRespone2e = """{"version":"1.5.0-final","correlationID":"session-12345","score":{"partAndParcel":"LOW","financialRisk":"LOW","personalService":"HIGH","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Inside IR35"}"""



  val decisionCase3a = """{"version":"1.5.0-final","correlationID":"session-829e8d15-12345-4988-b825-94c59db392a7","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""

  val decisionRespone3 = """{"version":"1.5.0-final","correlationID":"session-829e8d15-12345-4988-b825-94c59db392a7","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase3e = """{"version":"1.5.0-final","correlationID":"session-829e8d15-12345-4988-b825-94c59db392a7","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldNotReject","wouldWorkerPayHelper":true},"control":{"engagerMovingWorker":"cannotMoveWorkerWithoutNewAgreement","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerDecideSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"asPartOfUsualRateInWorkingHours"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""

  val decisionRespone3e = """{"version":"1.5.0-final","correlationID":"session-829e8d15-12345-4988-b825-94c59db392a7","score":{"exit":"CONTINUE","control":"OUTOFIR35","setup":"CONTINUE"},"result":"Outside IR35"}"""



  val decisionCase4a =  """{"version":"1.5.0-final","correlationID":"session-72dc03fc-c41e-49be-bee3-f207fb21e8ec","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone4 = """{"version":"1.5.0-final","correlationID":"session-72dc03fc-c41e-49be-bee3-f207fb21e8ec","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

    val decisionCase4e =  """{"version":"1.5.0-final","correlationID":"session-72dc03fc-c41e-49be-bee3-f207fb21e8ec","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithoutPermission","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"workerAgreeWithOthers"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":true,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"noObligationToCorrect"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""
  val decisionRespone4e = """{"version":"1.5.0-final","correlationID":"session-72dc03fc-c41e-49be-bee3-f207fb21e8ec","score":{"partAndParcel":"LOW","financialRisk":"MEDIUM","personalService":"HIGH","exit":"CONTINUE","control":"HIGH","setup":"CONTINUE"},"result":"Inside IR35"}"""



  val decisionCase5a = """{"version":"1.5.0-final","correlationID":"session-4ab87a6b-2dea-49db-a519-650a12ae06b1","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone5 = """{"version":"1.5.0-final","correlationID":"session-4ab87a6b-2dea-49db-a519-650a12ae06b1","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase5e = """{"version":"1.5.0-final","correlationID":"session-4ab87a6b-2dea-49db-a519-650a12ae06b1","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"cannotMoveWorkerWithoutNewAgreement","workerDecidingHowWorkIsDone":"workerDecidesWithoutInput","whenWorkHasToBeDone":"workerDecideSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":true,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"noObligationToCorrect"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""
  val decisionRespone5e = """{"version":"1.5.0-final","correlationID":"session-4ab87a6b-2dea-49db-a519-650a12ae06b1","score":{"exit":"CONTINUE","control":"OUTOFIR35","setup":"CONTINUE"},"result":"Outside IR35"}"""



  val decisionCase6a = """{"version":"1.5.0-final","correlationID":"session-425437df-24ce-4e97-8537-d521697277d5","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone6 = """{"version":"1.5.0-final","correlationID":"session-425437df-24ce-4e97-8537-d521697277d5","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase6e = """{"version":"1.5.0-final","correlationID":"session-425437df-24ce-4e97-8537-d521697277d5","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"cannotMoveWorkerWithoutNewAgreement","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"noScheduleRequiredOnlyDeadlines","workerDecideWhere":"workerAgreeWithOthers"},"financialRisk":{"workerProvidedMaterials":true,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":true,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"noObligationToCorrect"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":false}}}"""
  val decisionRespone6e = """{"version":"1.5.0-final","correlationID":"session-425437df-24ce-4e97-8537-d521697277d5","score":{"financialRisk":"OUTOFIR35","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Outside IR35"}"""


  val decisionCase7a = """{"version":"1.5.0-final","correlationID":"session-3015fd77-c21b-4b49-b166-ff6170b834c8","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone7 = """{"version":"1.5.0-final","correlationID":"session-3015fd77-c21b-4b49-b166-ff6170b834c8","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""


  val decisionCase7e = """{"version":"1.5.0-final","correlationID":"session-3015fd77-c21b-4b49-b166-ff6170b834c8","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithoutPermission","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"noObligationToCorrect"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""
  val decisionRespone7e = """{"version":"1.5.0-final","correlationID":"session-3015fd77-c21b-4b49-b166-ff6170b834c8","score":{"partAndParcel":"LOW","financialRisk":"LOW","personalService":"HIGH","exit":"CONTINUE","control":"HIGH","setup":"CONTINUE"},"result":"Inside IR35"}"""


  val decisionCase8a = """{"version":"1.5.0-final","correlationID":"session-8cbd115f-d486-46d8-ba89-1d7531c96479","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone8 = """{"version":"1.5.0-final","correlationID":"session-8cbd115f-d486-46d8-ba89-1d7531c96479","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase8e = """{"version":"1.5.0-final","correlationID":"session-8cbd115f-d486-46d8-ba89-1d7531c96479","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithPermission","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"noObligationToCorrect"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":true,"contactWithEngagerCustomer":false}}}"""
  val decisionRespone8e = """{"version":"1.5.0-final","correlationID":"session-8cbd115f-d486-46d8-ba89-1d7531c96479","score":{"partAndParcel":"HIGH","financialRisk":"LOW","personalService":"HIGH","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Inside IR35"}"""



  val decisionCase9a = """{"version":"1.5.0-final","correlationID":"session-a9aed912-33b1-49ad-b972-72b5d8c65be0","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone9 = """{"version":"1.5.0-final","correlationID":"session-a9aed912-33b1-49ad-b972-72b5d8c65be0","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase9e = """{"version":"1.5.0-final","correlationID":"session-a9aed912-33b1-49ad-b972-72b5d8c65be0","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithPermission","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"workerAgreeWithOthers"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"outsideOfHoursNoCosts"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""
  val decisionRespone9e = """{"version":"1.5.0-final","correlationID":"session-a9aed912-33b1-49ad-b972-72b5d8c65be0","score":{"partAndParcel":"LOW","financialRisk":"LOW","personalService":"HIGH","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Inside IR35"}"""


  val decisionCase10a = """{"version":"1.5.0-final","correlationID":"session-30128ec4-15e1-4ff0-a487-3dc866f8d25d","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone10 = """{"version":"1.5.0-final","correlationID":"session-30128ec4-15e1-4ff0-a487-3dc866f8d25d","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase10e = """{"version":"1.5.0-final","correlationID":"session-30128ec4-15e1-4ff0-a487-3dc866f8d25d","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"yesClientAgreed","workerPayActualSubstitute":false,"wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithPermission","workerDecidingHowWorkIsDone":"workerDecidesWithoutInput","whenWorkHasToBeDone":"noScheduleRequiredOnlyDeadlines","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":true,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeFixed","paidForSubstandardWork":"outsideOfHoursNoCharge"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":false}}}"""
  val decisionRespone10e = """{"version":"1.5.0-final","correlationID":"session-30128ec4-15e1-4ff0-a487-3dc866f8d25d","score":{"financialRisk":"OUTOFIR35","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Outside IR35"}"""


  val decisionCase11a = """"""
  val decisionRespone11 = """{"version":"1.5.0-final","correlationID":"session-72dc03fc-c41e-49be-bee3-f207fb21e8ec","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase11b = """"""
  val decisionRespone11b = """{"version":"1.5.0-final","correlationID":"session-72dc03fc-c41e-49be-bee3-f207fb21e8ec","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"HIGH","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase11c = """"""
  val decisionRespone11c = """{"version":"1.5.0-final","correlationID":"session-72dc03fc-c41e-49be-bee3-f207fb21e8ec","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"NotValidUseCase","control":"HIGH","setup":"CONTINUE"},"result":"Not Matched"}"""


  val decisionCase11d = """"""
  val decisionRespone11d = """{"version":"1.5.0-final","correlationID":"session-72dc03fc-c41e-49be-bee3-f207fb21e8ec","score":{"partAndParcel":"NotValidUseCase","financialRisk":"MEDIUM","personalService":"NotValidUseCase","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase11e = """"""
  val decisionRespone11e = """{"version":"1.5.0-final","correlationID":"session-72dc03fc-c41e-49be-bee3-f207fb21e8ec","score":{"partAndParcel":"LOW","financialRisk":"MEDIUM","personalService":"HIGH","exit":"CONTINUE","control":"HIGH","setup":"CONTINUE"},"result":"Inside IR35"}"""


  val decisionCase12a = """{"version":"1.5.0-final","correlationID":"session-8975db1b-80d7-4c76-85d6-03a25c558925","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone12 = """{"version":"1.5.0-final","correlationID":"session-8975db1b-80d7-4c76-85d6-03a25c558925","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase12b = """{"version":"1.5.0-final","correlationID":"session-8975db1b-80d7-4c76-85d6-03a25c558925","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldNotReject","possibleSubstituteWorkerPay":false,"wouldWorkerPayHelper":false}}}"""
  val decisionRespone12b = """{"version":"1.5.0-final","correlationID":"session-8975db1b-80d7-4c76-85d6-03a25c558925","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"MEDIUM","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase12c = """{"version":"1.5.0-final","correlationID":"session-8975db1b-80d7-4c76-85d6-03a25c558925","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"control":{"engagerMovingWorker":"cannotMoveWorkerWithoutNewAgreement","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"scheduleDecidedForWorker","workerDecideWhere":"noLocationRequired"}}}"""
  val decisionRespone12c = """{"version":"1.5.0-final","correlationID":"session-8975db1b-80d7-4c76-85d6-03a25c558925","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"NotValidUseCase","control":"MEDIUM","setup":"CONTINUE"},"result":"Not Matched"}"""


  val decisionCase12d = """{"version":"1.5.0-final","correlationID":"session-8975db1b-80d7-4c76-85d6-03a25c558925","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":true,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"asPartOfUsualRateInWorkingHours"}}}"""
  val decisionRespone12d = """{"version":"1.5.0-final","correlationID":"session-8975db1b-80d7-4c76-85d6-03a25c558925","score":{"financialRisk":"OUTOFIR35","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Outside IR35"}"""

  val decisionCase12e = """{"version":"1.5.0-final","correlationID":"session-8975db1b-80d7-4c76-85d6-03a25c558925","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldNotReject","possibleSubstituteWorkerPay":false,"wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"cannotMoveWorkerWithoutNewAgreement","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"scheduleDecidedForWorker","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":true,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"asPartOfUsualRateInWorkingHours"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""
  val decisionRespone12e = """{"version":"1.5.0-final","correlationID":"session-8975db1b-80d7-4c76-85d6-03a25c558925","score":{"financialRisk":"OUTOFIR35","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Outside IR35"}"""


  val decisionCase13a = """{"version":"1.5.0-final","correlationID":"session-f49e56a6-b690-4c06-a0d8-f82f836a58d7","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone13 = """{"version":"1.5.0-final","correlationID":"session-f49e56a6-b690-4c06-a0d8-f82f836a58d7","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase13b = """{"version":"1.5.0-final","correlationID":"session-f49e56a6-b690-4c06-a0d8-f82f836a58d7","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldNotReject","possibleSubstituteWorkerPay":false,"wouldWorkerPayHelper":false}}}"""
  val decisionRespone13b = """{"version":"1.5.0-final","correlationID":"session-f49e56a6-b690-4c06-a0d8-f82f836a58d7","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"MEDIUM","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase13c = """{"version":"1.5.0-final","correlationID":"session-f49e56a6-b690-4c06-a0d8-f82f836a58d7","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"control":{"engagerMovingWorker":"cannotMoveWorkerWithoutNewAgreement","workerDecidingHowWorkIsDone":"workerDecidesWithoutInput","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"noLocationRequired"}}}"""
  val decisionRespone13c = """{"version":"1.5.0-final","correlationID":"session-f49e56a6-b690-4c06-a0d8-f82f836a58d7","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"NotValidUseCase","control":"MEDIUM","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase13d = """{"version":"1.5.0-final","correlationID":"session-f49e56a6-b690-4c06-a0d8-f82f836a58d7","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":true,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"outsideOfHoursNoCosts"}}}"""
  val decisionRespone13d = """{"version":"1.5.0-final","correlationID":"session-f49e56a6-b690-4c06-a0d8-f82f836a58d7","score":{"financialRisk":"OUTOFIR35","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Outside IR35"}"""

  val decisionCase13e = """{"version":"1.5.0-final","correlationID":"session-f49e56a6-b690-4c06-a0d8-f82f836a58d7","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldNotReject","possibleSubstituteWorkerPay":false,"wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"cannotMoveWorkerWithoutNewAgreement","workerDecidingHowWorkIsDone":"workerDecidesWithoutInput","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":true,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"outsideOfHoursNoCosts"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workForEndClient"}}}"""
  val decisionRespone13e = """{"version":"1.5.0-final","correlationID":"session-f49e56a6-b690-4c06-a0d8-f82f836a58d7","score":{"financialRisk":"OUTOFIR35","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Outside IR35"}"""



  val decisionCase14a = """{"version":"1.5.0-final","correlationID":"session-7ff64104-e39b-4e75-8960-3bccbcb7df23","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone14 = """{"version":"1.5.0-final","correlationID":"session-7ff64104-e39b-4e75-8960-3bccbcb7df23","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase14b = """{"version":"1.5.0-final","correlationID":"session-7ff64104-e39b-4e75-8960-3bccbcb7df23","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false}}}"""
  val decisionRespone14b = """{"version":"1.5.0-final","correlationID":"session-7ff64104-e39b-4e75-8960-3bccbcb7df23","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"HIGH","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase14c = """{"version":"1.5.0-final","correlationID":"session-7ff64104-e39b-4e75-8960-3bccbcb7df23","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"control":{"engagerMovingWorker":"canMoveWorkerWithPermission","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerDecideSchedule","workerDecideWhere":"noLocationRequired"}}}"""
  val decisionRespone14c = """{"version":"1.5.0-final","correlationID":"session-7ff64104-e39b-4e75-8960-3bccbcb7df23","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"NotValidUseCase","control":"MEDIUM","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase14d = """{"version":"1.5.0-final","correlationID":"session-7ff64104-e39b-4e75-8960-3bccbcb7df23","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":true,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"outsideOfHoursNoCharge"}}}"""
  val decisionRespone14d = """{"version":"1.5.0-final","correlationID":"session-7ff64104-e39b-4e75-8960-3bccbcb7df23","score":{"financialRisk":"OUTOFIR35","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Outside IR35"}"""

  val decisionCase14e = """{"version":"1.5.0-final","correlationID":"session-7ff64104-e39b-4e75-8960-3bccbcb7df23","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithPermission","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerDecideSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":true,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"outsideOfHoursNoCharge"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""
  val decisionRespone14e = """{"version":"1.5.0-final","correlationID":"session-7ff64104-e39b-4e75-8960-3bccbcb7df23","score":{"financialRisk":"OUTOFIR35","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Outside IR35"}"""



  val decisionCase15a = """{"version":"1.5.0-final","correlationID":"session-b2d2388f-b241-4957-8141-2d0c5c0836a2","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone15 = """{"version":"1.5.0-final","correlationID":"session-b2d2388f-b241-4957-8141-2d0c5c0836a2","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase15b = """{"version":"1.5.0-final","correlationID":"session-b2d2388f-b241-4957-8141-2d0c5c0836a2","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false}}}"""
  val decisionRespone15b = """{"version":"1.5.0-final","correlationID":"session-b2d2388f-b241-4957-8141-2d0c5c0836a2","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"HIGH","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase15c = """{"version":"1.5.0-final","correlationID":"session-b2d2388f-b241-4957-8141-2d0c5c0836a2","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"control":{"engagerMovingWorker":"cannotMoveWorkerWithoutNewAgreement","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"noLocationRequired"}}}"""
  val decisionRespone15c = """{"version":"1.5.0-final","correlationID":"session-b2d2388f-b241-4957-8141-2d0c5c0836a2","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"NotValidUseCase","control":"MEDIUM","setup":"CONTINUE"},"result":"Not Matched"}"""


  val decisionCase15d = """{"version":"1.5.0-final","correlationID":"session-b2d2388f-b241-4957-8141-2d0c5c0836a2","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":true,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"outsideOfHoursNoCharge"}}}"""
  val decisionRespone15d = """{"version":"1.5.0-final","correlationID":"session-b2d2388f-b241-4957-8141-2d0c5c0836a2","score":{"financialRisk":"OUTOFIR35","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Outside IR35"}"""

  val decisionCase15e = """{"version":"1.5.0-final","correlationID":"session-b2d2388f-b241-4957-8141-2d0c5c0836a2","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"cannotMoveWorkerWithoutNewAgreement","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":true,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"outsideOfHoursNoCharge"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":false}}}"""
  val decisionRespone15e = """{"version":"1.5.0-final","correlationID":"session-b2d2388f-b241-4957-8141-2d0c5c0836a2","score":{"financialRisk":"OUTOFIR35","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Outside IR35"}"""



  val decisionCase16a = """{"version":"1.5.0-final","correlationID":"session-f757b601-7eec-46db-8024-652e6d425957","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone16 = """{"version":"1.5.0-final","correlationID":"session-f757b601-7eec-46db-8024-652e6d425957","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase16b = """{"version":"1.5.0-final","correlationID":"session-f757b601-7eec-46db-8024-652e6d425957","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false}}}"""
  val decisionRespone16b = """{"version":"1.5.0-final","correlationID":"session-f757b601-7eec-46db-8024-652e6d425957","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"HIGH","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase16c = """{"version":"1.5.0-final","correlationID":"session-f757b601-7eec-46db-8024-652e6d425957","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"control":{"engagerMovingWorker":"canMoveWorkerWithoutPermission","workerDecidingHowWorkIsDone":"workerAgreeWithOthers","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"noLocationRequired"}}}"""
  val decisionRespone16c = """{"version":"1.5.0-final","correlationID":"session-f757b601-7eec-46db-8024-652e6d425957","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"NotValidUseCase","control":"HIGH","setup":"CONTINUE"},"result":"Not Matched"}"""


  val decisionCase16d = """{"version":"1.5.0-final","correlationID":"session-f757b601-7eec-46db-8024-652e6d425957","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"asPartOfUsualRateInWorkingHours"}}}"""
  val decisionRespone16d = """{"version":"1.5.0-final","correlationID":"session-f757b601-7eec-46db-8024-652e6d425957","score":{"partAndParcel":"NotValidUseCase","financialRisk":"LOW","personalService":"NotValidUseCase","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase16e = """{"version":"1.5.0-final","correlationID":"session-f757b601-7eec-46db-8024-652e6d425957","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithoutPermission","workerDecidingHowWorkIsDone":"workerAgreeWithOthers","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"asPartOfUsualRateInWorkingHours"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":false}}}"""
  val decisionRespone16e = """{"version":"1.5.0-final","correlationID":"session-f757b601-7eec-46db-8024-652e6d425957","score":{"partAndParcel":"LOW","financialRisk":"LOW","personalService":"HIGH","exit":"CONTINUE","control":"HIGH","setup":"CONTINUE"},"result":"Inside IR35"}"""




  val decisionCase17a = """{"version":"1.5.0-final","correlationID":"session-4d138f6f-3656-4044-ba7d-6a8540e094dc","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone17 = """{"version":"1.5.0-final","correlationID":"session-4d138f6f-3656-4044-ba7d-6a8540e094dc","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase17b = """{"version":"1.5.0-final","correlationID":"session-4d138f6f-3656-4044-ba7d-6a8540e094dc","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false}}}"""
  val decisionRespone17b = """{"version":"1.5.0-final","correlationID":"session-4d138f6f-3656-4044-ba7d-6a8540e094dc","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"HIGH","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase17c = """{"version":"1.5.0-final","correlationID":"session-4d138f6f-3656-4044-ba7d-6a8540e094dc","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"control":{"engagerMovingWorker":"canMoveWorkerWithPermission","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"noScheduleRequiredOnlyDeadlines","workerDecideWhere":"workerCannotChoose"}}}"""
  val decisionRespone17c = """{"version":"1.5.0-final","correlationID":"session-4d138f6f-3656-4044-ba7d-6a8540e094dc","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"NotValidUseCase","control":"HIGH","setup":"CONTINUE"},"result":"Not Matched"}"""


  val decisionCase17d = """{"version":"1.5.0-final","correlationID":"session-4d138f6f-3656-4044-ba7d-6a8540e094dc","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"outsideOfHoursNoCharge"}}}"""
  val decisionRespone17d = """{"version":"1.5.0-final","correlationID":"session-4d138f6f-3656-4044-ba7d-6a8540e094dc","score":{"partAndParcel":"NotValidUseCase","financialRisk":"MEDIUM","personalService":"NotValidUseCase","exit":"NotValidUseCase","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase17e = """{"version":"1.5.0-final","correlationID":"session-4d138f6f-3656-4044-ba7d-6a8540e094dc","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithPermission","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"noScheduleRequiredOnlyDeadlines","workerDecideWhere":"workerCannotChoose"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"outsideOfHoursNoCharge"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""
  val decisionRespone17e = """{"version":"1.5.0-final","correlationID":"session-4d138f6f-3656-4044-ba7d-6a8540e094dc","score":{"partAndParcel":"LOW","financialRisk":"MEDIUM","personalService":"HIGH","exit":"CONTINUE","control":"HIGH","setup":"CONTINUE"},"result":"Inside IR35"}"""




  val decisionCase18a = """{"version":"1.5.0-final","correlationID":"session-e7d07a17-3cfe-4ff6-bcca-cda7d0eb651e","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone18 = """{"version":"1.5.0-final","correlationID":"session-e7d07a17-3cfe-4ff6-bcca-cda7d0eb651e","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase18e = """{"version":"1.5.0-final","correlationID":"session-e7d07a17-3cfe-4ff6-bcca-cda7d0eb651e","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithPermission","workerDecidingHowWorkIsDone":"workerDecidesWithoutInput","whenWorkHasToBeDone":"workerDecideSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":true,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"asPartOfUsualRateInWorkingHours"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":false}}}"""
  val decisionRespone18e = """{"version":"1.5.0-final","correlationID":"session-e7d07a17-3cfe-4ff6-bcca-cda7d0eb651e","score":{"financialRisk":"OUTOFIR35","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Outside IR35"}"""



  val decisionCase19a = """{"version":"1.5.0-final","correlationID":"session-6dc80962-346a-4c25-b5a6-7d08cabee4c9","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone19 = """{"version":"1.5.0-final","correlationID":"session-6dc80962-346a-4c25-b5a6-7d08cabee4c9","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""


  val decisionCase19e = """{"version":"1.5.0-final","correlationID":"session-6dc80962-346a-4c25-b5a6-7d08cabee4c9","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithPermission","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":true,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":false,"workerMainIncome":"incomeFixed","paidForSubstandardWork":"cannotBeCorrected"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""
  val decisionRespone19e = """{"version":"1.5.0-final","correlationID":"session-6dc80962-346a-4c25-b5a6-7d08cabee4c9","score":{"financialRisk":"OUTOFIR35","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Outside IR35"}"""


  val decisionCase20a = """{"version":"1.5.0-final","correlationID":"session-685d7f4f-92c3-49c2-9520-09836fa0390b","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone20 = """{"version":"1.5.0-final","correlationID":"session-685d7f4f-92c3-49c2-9520-09836fa0390b","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""


  val decisionCase20e = """{"version":"1.5.0-final","correlationID":"session-685d7f4f-92c3-49c2-9520-09836fa0390b","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldNotReject","possibleSubstituteWorkerPay":false,"wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"cannotMoveWorkerWithoutNewAgreement","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"outsideOfHoursNoCharge"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workAsIndependent"}}}"""
  val decisionRespone20e = """{"version":"1.5.0-final","correlationID":"session-685d7f4f-92c3-49c2-9520-09836fa0390b","score":{"partAndParcel":"LOW","financialRisk":"MEDIUM","personalService":"MEDIUM","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Unknown"}"""


  val decisionCase21a = """{"version":"1.5.0-final","correlationID":"session-bb2b9dee-2599-4494-9c4d-324709e81adc","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone21 = """{"version":"1.5.0-final","correlationID":"session-bb2b9dee-2599-4494-9c4d-324709e81adc","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""


  val decisionCase21e = """{"version":"1.5.0-final","correlationID":"session-bb2b9dee-2599-4494-9c4d-324709e81adc","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"limitedCompany"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldReject","wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"canMoveWorkerWithoutPermission","workerDecidingHowWorkIsDone":"workerFollowStrictEmployeeProcedures","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"noLocationRequired"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"asPartOfUsualRateInWorkingHours"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":false}}}"""
  val decisionRespone21e = """{"version":"1.5.0-final","correlationID":"session-bb2b9dee-2599-4494-9c4d-324709e81adc","score":{"partAndParcel":"LOW","financialRisk":"LOW","personalService":"HIGH","exit":"CONTINUE","control":"HIGH","setup":"CONTINUE"},"result":"Inside IR35"}"""


  val decisionCase22a = """{"version":"1.5.0-final","correlationID":"session-72f6b69a-018e-4ad7-8589-a04658801d32","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{},"control":{},"financialRisk":{"expensesAreNotRelevantForRole":false},"partAndParcel":{}}}"""
  val decisionRespone22 = """{"version":"1.5.0-final","correlationID":"session-72f6b69a-018e-4ad7-8589-a04658801d32","score":{"partAndParcel":"NotValidUseCase","financialRisk":"NotValidUseCase","personalService":"NotValidUseCase","exit":"CONTINUE","control":"NotValidUseCase","setup":"CONTINUE"},"result":"Not Matched"}"""

  val decisionCase22e =  """{"version":"1.5.0-final","correlationID":"session-72f6b69a-018e-4ad7-8589-a04658801d32","interview":{"setup":{"endUserRole":"personDoingWork","hasContractStarted":true,"provideServices":"soleTrader"},"exit":{"officeHolder":false},"personalService":{"workerSentActualSubstitute":"noSubstitutionHappened","possibleSubstituteRejection":"wouldNotReject","possibleSubstituteWorkerPay":false,"wouldWorkerPayHelper":false},"control":{"engagerMovingWorker":"cannotMoveWorkerWithoutNewAgreement","workerDecidingHowWorkIsDone":"noWorkerInputAllowed","whenWorkHasToBeDone":"workerAgreeSchedule","workerDecideWhere":"workerCannotChoose"},"financialRisk":{"workerProvidedMaterials":false,"workerProvidedEquipment":false,"workerUsedVehicle":false,"workerHadOtherExpenses":false,"expensesAreNotRelevantForRole":true,"workerMainIncome":"incomeCalendarPeriods","paidForSubstandardWork":"cannotBeCorrected"},"partAndParcel":{"workerReceivesBenefits":false,"workerAsLineManager":false,"contactWithEngagerCustomer":true,"workerRepresentsEngagerBusiness":"workForEndClient"}}}"""
  val decisionRespone22e = """{"version":"1.5.0-final","correlationID":"session-72f6b69a-018e-4ad7-8589-a04658801d32","score":{"partAndParcel":"MEDIUM","financialRisk":"LOW","personalService":"MEDIUM","exit":"CONTINUE","control":"MEDIUM","setup":"CONTINUE"},"result":"Inside IR35"}"""



  // scalastyle:on

}
